#!/bin/bash

# --- COLORS ---
RED='\033[0;31m'
GREEN='\033[0;32m'
BG_GREEN='\033[0;30;42m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# --- INITIALIZATION ---
# echo -e "${YELLOW}**************************************************************${NC}"
# echo -e "${YELLOW}* Please make sure you include your design in your TESTBED.v *${NC}"
# echo -e "${YELLOW}**************************************************************${NC}"

# Clean up and Run Simulation
./09_clean_up > /dev/null 2>&1
./01_run_vcs_rtl > /dev/null 2>&1

# --- RESULT CHECKING ---

if grep -i -q 'FAIL' 'vcs.log'; then
  echo -e "${RED}--- 01_RTL PATTERN Fail !! ---${NC}"
  exit 1

elif grep -i -q 'Congratulations' 'vcs.log'; then
  echo -e "${BG_GREEN}--- 01_RTL PATTERN PASS !! ---${NC}"
  
  # Extract Latency from vcs.log
  Latency=$(grep 'execution cycles =' vcs.log | grep -Eo '[0-9]+' | head -n 1)
  
  # Extract Cycle Time from vcs.log
  Cycle=$(grep 'clock period =' vcs.log | grep -Eo '[0-9]+(\.[0-9]+)?' | head -n 1)

  if [[ -n "$Latency" ]]; then
    echo -e "${BG_GREEN}Execution cycles:${NC} ${Latency} cycles"
  fi
  if [[ -n "$Cycle" ]]; then
    echo -e "${BG_GREEN}Cycle Time:${NC} ${Cycle} ns"
  fi

else
  echo -e "${RED}--- 01_RTL wrong !! ---${NC}"
  exit 1
fi

exit 0
